- name: Copy Docker Compose file
  ansible.builtin.copy:
    src: "{{ docker_compose_src }}"
    dest: "{{ target_dir }}/docker-compose.yaml"
  register: docker_compose_copy

- name: Stop and remove existing containers
  ansible.builtin.command:
    cmd: docker-compose down
    chdir: "{{ target_dir }}"
  ignore_errors: true
  when: down_before_start is defined and down_before_start

- name: Start Docker Compose
  ansible.builtin.command:
    cmd: docker-compose up -d
    chdir: "{{ target_dir }}"
  environment: "{{ docker_compose_env }}"
  when: docker_compose_copy is changed or down_before_start is defined and down_before_start