name: go-base-api
networks:
  app-network:
    driver: bridge
services:
  api:
    build:
      context: ..
      dockerfile: cmd/api/Dockerfile
    hostname: api
    networks:
        - app-network
    environment:
      - GIN_MODE=debug
    ports:
      - "8899:8899"
    volumes:
      - ../config_gen.json:/config/config.json
      - ../logs/api:/var/logs
  dash:
    build:
      context: ..
      dockerfile: cmd/dash/Dockerfile
    hostname: dash
    networks:
      - app-network
    depends_on:
      api:
        condition: service_started
    ports:
      - "8800:8800"
    volumes:
      - ../config_gen.json:/config/config.json
      - ../logs/dash:/var/logs/
