version: '3'

services:
  api:
    build:
      context: ..
      dockerfile: ../example/cmd/api/Dockerfile
    hostname: api
    networks:
        - app-network
    environment:
      - GIN_MODE=debug
    ports:
      - "8899:8899"
    volumes:
      - ${LOG_PATH:-/opt/base-api/logs/api}:/var/logs
      - ${CONFIG_PATH:-/opt/base-api/config/api}:/config
  dash:
    build:
      context: ..
      dockerfile: ../example/cmd/dash/Dockerfile
    hostname: dash
    networks:
      - app-network
    depends_on:
      api:
        condition: service_started
    ports:
      - "8800:8800"
    volumes:
       - ${LOG_PATH:-/opt/base-api/logs/dash}:/var/logs
       - ${CONFIG_PATH:-/opt/base-api/config/dash}:/config

networks:
  app-network:
    driver: bridge
