---
- name: Build and deploy
  hosts: web_servers
  become: true

  vars:
    project_dir: "{{ playbook_dir }}/../"
    build_dir: "{{ project_dir }}/build/linux_x86"
    deploy_dir: "/usr/local/bin"
    force_overwrite: false

  tasks:
    - name: Build the binary
      become: false
      ansible.builtin.command:
        cmd: "make buildLinuxX86"
        chdir: "{{ project_dir }}"
      delegate_to: localhost
      register: build_result
      changed_when: build_result.rc == 0
      failed_when: build_result.rc != 0
      run_once: true

    - name: Deploy app
      include_role:
        name: deploy_app
      vars:
        binary_name: "cli"
        systemd_name: "base-api"
        config_dest: "/etc/base-api/config.json"
        config_source: "{{ project_dir }}/config_gen.json"
        exec_start: "{{ deploy_dir }}/{{ binary_name }} start -c {{ config_dest }}" 

    - name: Deploy nginx
      include_role:
        name: nginx_proxy
      vars:
        server_name: "base-api"
        servers:
          - name: "api.debian-amd.orb.local"
            locations:
              - path: "/"
                proxy_pass: "http://127.0.0.1:8899"
          - name: "dash.debian-amd.orb.local"
            locations:
              - path: "/"
                proxy_pass: "http://127.0.0.1:8800"

