---
- name: Deploy MariaDB
  hosts: web_servers
  become: "{{ ansible_become | default(true) }}"
  connection: "{{ ansible_connection | default('ssh') }}"

  vars:
    down_before_start: true
    root_dir: "{{ ansible_opt_dir | default('/opt') }}"
    mariadb_dir: "{{ root_dir }}/mariadb"
    mariadb_data_dir: "{{ mariadb_dir }}/data"

  tasks:
    - name: Ensure MariaDB directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ mariadb_dir }}"
        - "{{ mariadb_data_dir }}"

    - name: Deploy MariaDB
      include_role:
        name: deploy_compose
      vars:
        target_dir: "{{ mariadb_dir }}"
        docker_compose_src: ./mariadb/docker-compose.yaml
        docker_compose_env:
          MARIADB_DATA_DIR: "{{ mariadb_data_dir }}"

    - name: Wait for MariaDB to be ready
      ansible.builtin.wait_for:
        host: localhost
        port: 3306
        state: started
        delay: 10
        timeout: 60