project_root: "{{ playbook_dir }}/../.."
service_name: "app"
binary_name: "app"

# User Group
service_user: "{{ service_name }}_user"
service_group: "{{ service_name }}_group"
create_system_user: true

# Bin Path
local_bin_path: "{{ project_root }}/build/linux_amd64/{{ binary_name }}"
remote_bin_path: "/usr/local/bin/{{ binary_name }}"

# Configuration Path
conf_dir: "/etc/{{ service_name }}"
conf_file: "config.json"
local_config_path: "{{ project_root }}/config.json"

# Service
unit_name: "{{ service_name }}_service"
exec_args: "--config {{ conf_dir }}/{{ conf_file }}"

# Security
force_restart: false
enable_service: true