version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    hostname: mariadb
    environment:
      MARIADB_DATABASE: go-base
      MARIADB_USER: api
      MARIADB_PASSWORD: password
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /opt/mariadb/data:/var/lib/mysql
    command: >
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5