---
- name: Deploy MariaDB
  hosts: web_servers
  become: "{{ ansible_become | default(true) }}"
  connection: "{{ ansible_connection | default('ssh') }}"

  vars:
    root_dir: "{{ ansible_opt_dir | default('/opt') }}"
    mariadb_dir: "{{ root_dir }}/mariadb"
    mariadb_data_dir: "{{ mariadb_dir }}/data"

  tasks:
    - name: Ensure MariaDB directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ mariadb_dir }}"
        - "{{ mariadb_data_dir }}"

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: ./docker-compose.yaml
        dest: "{{ mariadb_dir }}/docker-compose.yaml"
      register: docker_compose_copy

    - name: Start Docker Compose
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: "{{ mariadb_dir }}"
      environment:
        MARIADB_DATA_DIR: "{{ mariadb_data_dir }}"
      when: docker_compose_copy is changed

    - name: Wait for MariaDB to be ready
      ansible.builtin.wait_for:
        host: localhost
        port: 3306
        state: started
        delay: 10
        timeout: 60