---
- name: Deploy Loki Stack with Nginx
  hosts: web_servers
  become: "{{ ansible_become | default(true) }}"
  connection: "{{ ansible_connection | default('ssh') }}"
  
  vars:
    root_dir: "{{ ansible_opt_dir | default('/opt') }}"
    loki_dir: "{{ root_dir }}/loki"
    log_path: /var/logs 
    down_before_start: true
    # grafana_nginx_config:
    #   domain: "consul.debian-amd.orb.local"
    #   location: "/"
    #   proxy_pass: "http://127.0.0.1:3000"

  tasks:
    - name: Ensure Loki directory exists
      ansible.builtin.file:
        path: "{{ loki_dir }}"
        state: directory
        mode: '0755'

    - name: Deploy Loki
      include_role:
        name: deploy_compose
      vars:
        target_dir: "{{ loki_dir }}"
        docker_compose_src: ./loki/docker-compose.yaml
        docker_compose_env:
          LOG_PATH: "{{ log_path }}"

    - name: Setup Nginx for Grafana
      include_role:
        name: nginx_proxy
      vars:
        server_name: "grafana"
        servers:
          - name: "{{ grafana_nginx_config.domain }}"
            locations:
              - path: "{{ grafana_nginx_config.location }}"
                proxy_pass: "{{ grafana_nginx_config.proxy_pass }}"
      when: grafana_nginx_config is defined

  handlers:
    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded