---
- name: Create deployment directories
  file:
    path: "{{ item.context }}"
    state: directory
    mode: '0755'
  loop: "{{ services }}"

- name: Copy executable binary files
  copy:
    src: "{{ item.binary_src_path }}"
    dest: "{{ item.binary_dest_path }}"
    mode: '0755'
  loop: "{{ services }}"
  when: item.binary_src_path is defined and item.binary_name is defined

- name: Copy Dockerfile templates
  template:
    src: "{{ item.dockerfile_template | default('Dockerfile.j2') }}"
    dest: "{{ item.context }}/Dockerfile"
  vars:
    binary_name: "{{ item.binary_name }}"
    envs: "{{ item.envs | default({}) }}"
    cmd_args: "{{ item.cmd_args | default('') }}"
  loop: "{{ services }}"

- name: Copy docker-compose.yaml template
  template:
    src: docker-compose.yaml.j2
    dest: "{{ deploy_dir }}/docker-compose.yaml"

- name: Docker compose up
  community.docker.docker_compose:
    project_src: "{{ deploy_dir }}"
    files:
      - docker-compose.yaml
    state: present
    recreate: always
    build: true