version: '3'
name: consul

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"  # HTTP API and Web UI
      - "8600:8600/udp"  # DNS interface
    command: >
      agent -server 
      -ui 
      -node=server-1 
      -bootstrap-expect=1 
      -client=0.0.0.0 
      -config-file=/consul/config/acl.json
    volumes:
      - ${CONSUL_DATA_DIR:-/opt/consul/data}:/consul/data
      - ${CONSUL_CONFIG_DIR:-./config}:/consul/config
    networks:
      - consul-net

networks:
  consul-net:
    driver: bridge

volumes:
  consul-data:
