---
- name: Setup Consul with ACL
  hosts: web_servers
  become: yes
  
  vars:
    consul_root_dir: "/opt/consul"
    consul_config_dir: "{{ consul_root_dir }}/config"
    consul_data_dir: "{{ consul_root_dir }}/data"
    consul_files:
      - { src: './docker-compose.yaml', dest: 'docker-compose.yaml' }
      - { src: './config/acl.json', dest: 'config/acl.json' }

  tasks:
    - name: Create Consul directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ consul_root_dir }}"
        - "{{ consul_config_dir }}"
        - "{{ consul_data_dir }}"

    - name: Copy configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ consul_root_dir }}/{{ item.dest }}"
        mode: '0644'
      loop: "{{ consul_files }}"

    - name: Start Consul container
      community.docker.docker_compose:
        project_src: "{{ consul_root_dir }}"
        state: present
        pull: true
      environment:
        CONSUL_DATA_DIR: "{{ consul_data_dir }}"
        CONSUL_CONFIG_DIR: "{{ consul_config_dir }}"

    - name: Wait for Consul to start
      ansible.builtin.wait_for:
        port: 8500
        delay: 10

    - name: Bootstrap ACL system
      ansible.builtin.command: docker exec consul consul acl bootstrap
      register: acl_bootstrap
      changed_when: true
      retries: 3
      delay: 5
      until: acl_bootstrap.rc == 0

    - name: Display ACL token
      ansible.builtin.debug:
        var: acl_bootstrap.stdout_lines
