---
- name: Ensure NGINX is installed
  apt:
    name: nginx
    state: present
  become: true

- name: Ensure NGINX sites-available directory exists
  file:
    path: /etc/nginx/sites-available
    state: directory
  become: true

- name: Check if NGINX proxy configuration exists
  ansible.builtin.stat:
    path: "/etc/nginx/sites-available/{{ server_name }}.conf"
  register: nginx_config_stat

- name: Create or update NGINX proxy configuration
  template:
    src: nginx_proxy.conf.j2
    dest: "/etc/nginx/sites-available/{{ server_name }}.conf"
    mode: '0644'
  become: true
  when: not nginx_config_stat.stat.exists or force_overwrite | default(false)
  notify: Restart NGINX

- name: Ensure NGINX proxy configuration is enabled
  file:
    src: "/etc/nginx/sites-available/{{ server_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
    state: link
  become: true
  notify: Restart NGINX

- name: Remove default NGINX site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  notify: Restart NGINX
  when: remove_default_site | default(false)