- name: Copy Config
  ansible.builtin.copy:
    src: "{{ config_source }}"
    dest: "{{ config_dest }}"
    mode: '0644'
  become: true

- name: Deploy binary
  ansible.builtin.include_role:
    name: deploy_binary
  vars:
    config_file: "{{ config_dest }}"

